[package]
name = "snippet-compiler-rust"
version = "0.1.1"
edition = "2021"

[dependencies]
color-eyre.workspace = true
async-trait.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
wit-bindgen.workspace = true

[build-dependencies]
wit-deps.workspace = true
color-eyre.workspace = true

[lib]
crate-type = ["cdylib"]
