[package]
name = "snippet-compiler-clang"
version = "0.1.1"
edition = "2021"

[dependencies]
tracing.workspace = true
wit-bindgen.workspace = true

[build-dependencies]
wit-deps.workspace = true
color-eyre.workspace = true

[lib]
crate-type = ["cdylib"]
